version: '3.8'

services:
  nestjs-app:
    container_name: app
    build:
      context: .
      dockerfile: DockerfileDev
    ports:
      - '3000:3000'
    volumes:
      - .:/app
      - /app/node_modules
    command: yarn start:dev